#!/usr/bin/env bash

# don't fail fast
#set -eu

# Enable job control
set -m

process_slug() {
  local app_release=${1}

  echo "--> Processing $app_release"

  local app_release_array=($app_release)
  local app=${app_release_array[0]}
  local release=${app_release_array[1]}

  local slug_id=$(curl --retry 3 -s -n https://api.heroku.com/apps/$app/releases/$release \
    -H "Accept: application/vnd.heroku+json; version=3" | \
    python -c 'import json,sys;obj=json.load(sys.stdin);print obj["slug"]["id"]')

  if [ -n "$slug_id" ]; then
    local slug_url=$(curl --retry 3 -s -n https://api.heroku.com/apps/$app/slugs/$slug_id \
      -H "Accept: application/vnd.heroku+json; version=3" | \
      python -c 'import json,sys;obj=json.load(sys.stdin);print obj["blob"]["url"]')

    if [ -n "$slug_url" ]; then
      echo "--> Downloading slug ${slug_id} for ${app}"
      curl --retry 3 -s -L "${slug_url}" | \
          tar xzm --strip-components=1 -C . 2>&1 | \
          grep -v "Ignoring unknown extended header keyword"
    else
      echo "! ERROR: could not find slug $slug_id for $app_release"
    fi
  else
    echo "! ERROR: could not find release v${release} for ${app}"
  fi
}

[ -z "$HEROKU_API_KEY" ] && echo " ! ERROR: missing HEROKU_API_KEY config var" && exit 1
[ -z "$HEROKU_API_USER" ] && echo " ! ERROR: missing HEROKU_API_USER config var" && exit 1

if [ -f .nginx/bin/nginx-start ]; then
  cd .nginx > /dev/null 2>&1
  eval "bin/nginx-start &"
  pid=$!
  cd - > /dev/null 2>&1
  trap "kill -9 $pid; exit" SIGKILL
else
  echo "No .nginx/bin/nginx-start file found!"
fi

# create netrc
cat >> $HOME/.netrc <<EOF
machine api.heroku.com
  login $HEROKU_API_USER
  password $HEROKU_API_KEY
EOF

echo "" >> Appfile

echo "Reading Appfile..."
app_release=$(head -n 1 /app/Appfile)
if [ -n "$app_release" ]; then
  process_slug "$app_release"
fi
echo "Done reading Appfile."

rm $HOME/.netrc

echo "true" > $HOME/.recompose

java $BOOTSTRAP_JAVA_OPTS -jar zerobootstrap.jar
